############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: proxyserver002-service
  namespace: proxyserver002
spec:
  type: ExternalName
  externalName: 192.168.1.103
  ports:
  - port: 80
    targetPort: 80
---