############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  labels:
    name: unifi
    app: unifi
    owner: EliasDH
    environment: production
  annotations:
    description: This namespace is used for the unifi application.
    contact: info@eliasdh.com
---