############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: webserver004-frontend-service
  namespace: webserver004
spec:
  selector:
    app: webserver004-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---