############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }

    registry.eliasdh.com:53 {
        errors
        cache 30
        hosts {
            192.168.1.200 registry.eliasdh.com
            fallthrough
        }
    }

    netbox.buckingham.eliasdh.com:53 {
        errors
        cache 30
        hosts {
            192.168.1.200 netbox.buckingham.eliasdh.com
            fallthrough
        }
    }
---