############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-server-vanilla
  labels:
    name: minecraft-server-vanilla
    app: minecraft-server-vanilla
    owner: EliasDH
    environment: production
  annotations:
    description: This namespace is used for the minecraft server vanilla application.
    contact: info@eliasdh.com
---