############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-vanilla-service
  namespace: minecraft-server-vanilla
spec:
  selector:
    app: minecraft-server-vanilla
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.1.121
---