############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: netbox
data:
  db_name: netbox
  db_user: netbox
---