############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: netbox
data:
  ALLOWED_HOSTS: "netbox-buckingham.eliasdh.com"
  DB_HOST: "netbox-postgresql"
  DB_NAME: "netbox"
  DB_USER: "netbox"
  REDIS_HOST: "netbox-redis"
  REDIS_CACHE_HOST: "netbox-redis"
---