############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: netbox-housekeeping
  namespace: netbox
spec:
  schedule: "0 0 * * *" # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: housekeeping
            image: ghcr.io/eliasdh-com/netbox-topology-views:latest
            command: ["/opt/netbox/venv/bin/python", "/opt/netbox/netbox/manage.py", "housekeeping"]
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: secret_key
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: db_password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: redis_password
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: ALLOWED_HOSTS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: DB_USER
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: REDIS_HOST
            - name: REDIS_CACHE_HOST
              valueFrom:
                configMapKeyRef:
                  name: netbox-config
                  key: REDIS_CACHE_HOST
          restartPolicy: OnFailure
---