############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
metadata:
  name: cluster01
controlPlaneEndpoint: "10.1.0.10:6443"
networking:
  podSubnet: "10.244.0.0/16"
criSocket: "/run/containerd/containerd.sock"
---