############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver001-deployment
  namespace: webserver001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver001
  template:
    metadata:
      labels:
        app: webserver001
    spec:
      containers:
        - name: webserver001-container
          image: "ghcr.io/eliasdh-com/eliasdhcom-frontend:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---