############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: webserver002-service
  namespace: webserver002
spec:
  selector:
    app: webserver002
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---