############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver003-frontend-deployment
  namespace: webserver003
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver003
  template:
    metadata:
      labels:
        app: webserver003
    spec:
      containers:
        - name: webserver003-frontend-container
          image: "ghcr.io/eliasdh-com/applevelupbe-frontend:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver003-backend-deployment
  namespace: webserver003
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver003
  template:
    metadata:
      labels:
        app: webserver003
    spec:
      containers:
        - name: webserver003-backend-container
          image: "ghcr.io/eliasdh-com/applevelupbe-backend:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
---