apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          ports:
            - containerPort: 25565
              name: minecraft
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: "2G"
            - name: DIFFICULTY
              value: "normal"
            - name: MODE
              value: "creative"
            - name: MOTD
              value: "§a§lW§b§le§c§ll§d§lc§e§lo§f§lm§a§le §b§lt§c§lo §d§lE§e§ll§f§li§a§la§b§ls§c§lD§d§lH §e§lM§f§li§a§ln§b§le§c§lc§d§lr§e§la§f§lf§a§lt §b§lS§c§le§d§lr§e§lv§f§le§a§lr"
            - name: SPAWN_PROTECTION
              value: "0"
            - name: PVP
              value: "true"
            - name: ONLINE_MODE
              value: "true"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: minecraft-icon
              mountPath: /data/server-icon.png
              subPath: server-icon.png
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
        - name: minecraft-icon
          configMap:
            name: minecraft-icon
---