############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: default
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "2G"
        - name: DIFFICULTY
          value: "normal"
        - name: MODE
          value: "creative"
        - name: MOTD
          value: "Welcome to EliasDH Minecraft Server"
        - name: SPAWN_PROTECTION
          value: "0"
        - name: PVP
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "2"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc
---