############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          ports:
          - containerPort: 25565
            name: minecraft
          env:
          - name: EULA
            value: "TRUE"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
            - name: minecraft-icon
              mountPath: /data/server-icon.png
              subPath: server-icon.png
            - name: minecraft-config
              mountPath: /data/server.properties
              subPath: server.properties
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
        - name: minecraft-icon
          configMap:
            name: minecraft-icon
        - name: minecraft-config
          configMap:
            name: minecraft-config
---