############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    name: minecraft
    app: minecraft
    owner: EliasDH
    environment: production
  annotations:
    description: This namespace is used for the minecraft application.
    contact: info@eliasdh.com
---